# Generated by Django 2.2 on 2019-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gatelog_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerId', models.IntegerField()),
                ('workerName', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='heatmap_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('A', models.IntegerField(default=0)),
                ('B', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('D', models.IntegerField(default=0)),
                ('E', models.IntegerField(default=0)),
                ('F', models.IntegerField(default=0)),
                ('G', models.IntegerField(default=0)),
                ('H', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='worker_table',
            fields=[
                ('workerId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='暂无匹配姓名', max_length=30)),
                ('timeStart', models.CharField(max_length=30)),
                ('timeEffect', models.IntegerField()),
            ],
        ),
    ]
